import { c as create_ssr_component, a as subscribe, e as escape, v as validate_component } from "./ssr.js";
import { S as Sponsors } from "./Ads.js";
import { t } from "./i18n.js";
const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $t, $$unsubscribe_t;
  $$unsubscribe_t = subscribe(t, (value) => $t = value);
  const newtabicon = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="inline-block w-4 fill-current opacity-0 group-hover:opacity-50"><path fill-rule="evenodd" d="M19,14 L19,19 C19,20.1045695 18.1045695,21 17,21 L5,21 C3.8954305,21 3,20.1045695 3,19 L3,7 C3,5.8954305 3.8954305,5 5,5 L10,5 L10,7 L5,7 L5,19 L17,19 L17,14 L19,14 Z M18.9971001,6.41421356 L11.7042068,13.7071068 L10.2899933,12.2928932 L17.5828865,5 L12.9971001,5 L12.9971001,3 L20.9971001,3 L20.9971001,11 L18.9971001,11 L18.9971001,6.41421356 Z" /></svg>`;
  $$unsubscribe_t();
  return `<div><div class="bg-base-100 text-base-content"><footer class="footer mx-auto max-w-6xl px-4 py-20"><div><div class="flex items-center gap-2" data-svelte-h="svelte-1kdogt8"><svg width="32" height="32" viewBox="0 0 415 415" xmlns="http://www.w3.org/2000/svg"><rect x="82.5" y="290" width="250" height="125" rx="62.5" fill="#1AD1A5"></rect><circle cx="207.5" cy="135" r="130" fill="black" fill-opacity=".3"></circle><circle cx="207.5" cy="135" r="125" fill="white"></circle><circle cx="207.5" cy="135" r="56" fill="#FF9903"></circle></svg> <div class="font-title inline-flex text-3xl font-black"><span class="lowercase">daisy</span> <span class="uppercase text-[#1AD1A5]">UI</span></div></div> <p class="opacity-50"><!-- HTML_TAG_START -->${$t("footer-tagline")}<!-- HTML_TAG_END --></p> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/saadeghi/daisyui/blob/master/.github/CONTRIBUTING.md" class="link link-hover group">${escape($t("contributing"))} <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a href="/docs/changelog" class="link link-hover">${escape($t("changelog"))}</a> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/saadeghi/daisyui/blob/master/LICENSE" class="link link-hover group">${escape($t("license"))} <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/saadeghi/daisyui/discussions/1949" class="link link-hover group">FAQ
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a></div> <div><span class="footer-title">${escape($t("pages"))}</span> <a href="/docs/install/" class="link link-hover">${escape($t("how-to-install"))}</a> <a href="/docs/use/" class="link link-hover">${escape($t("how-to-use-components"))}</a> <a href="/docs/customize/" class="link link-hover">${escape($t("how-to-customize"))}</a> <a href="/docs/themes/" class="link link-hover">${escape($t("how-to-use-themes"))}</a> <a href="/docs/colors/" class="link link-hover">${escape($t("color-system"))}</a> <a href="/docs/config/" class="link link-hover">${escape($t("config"))}</a> <a href="/blog/" class="link link-hover">${escape($t("Blog"))}</a></div> <div><span class="footer-title">${escape($t("available-on"))}</span> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/saadeghi/daisyui" class="link link-hover group">Github
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://opencollective.com/daisyui" class="link link-hover group">OpenCollective
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://www.npmjs.com/package/daisyui" class="link link-hover group">NPM
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://unpkg.com/browse/daisyui/" class="link link-hover group">Unpkg CDN
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://www.jsdelivr.com/package/npm/daisyui" class="link link-hover group">JSdeliver CDN
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a></div> <div><span class="footer-title">${escape($t("try-online"))}</span> <a href="/tailwindplay" class="link link-hover group" target="_blank" rel="noopener, noreferrer">Tailwind Play
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="/codepen" class="link link-hover group">Codepen
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a></div> <div><span class="footer-title">${escape($t("related projects"))}</span> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/daisyui/react-daisyui" class="link link-hover group">React daisyUI
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/daief/daisyui-vue" class="link link-hover group">daisyUI Vue (WIP)
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/robsontenorio/mary" class="link link-hover group">Mary - Laravel components
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/kidonng/unocss-preset-daisy" class="link link-hover group">daisyUI UnoCSS preset
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a> <a target="_blank" rel="noopener, noreferrer" href="https://github.com/saadeghi/theme-change" class="link link-hover group">Theme Change
          <!-- HTML_TAG_START -->${newtabicon}<!-- HTML_TAG_END --></a></div></footer></div> <footer class="footer footer-center border-base-200 bg-base-200 text-base-content border-t px-4 py-4"><div class="flex w-full max-w-6xl flex-col items-center justify-between gap-6 sm:flex-row"><a href="https://github.com/saadeghi" rel="noopener, noreferrer" target="_blank" class="inline-flex items-center justify-center hover:opacity-90"><div class="avatar mr-3" data-svelte-h="svelte-18eql5n"><div class="mask mask-squircle bg-neutral h-14 w-14 p-px"><img loading="lazy" width="54" height="54" src="/pouya-saadeghi.jpg" alt="Pouya Saadeghi" class="mask mask-squircle"></div></div> <div class="text-left"><p class="text-base-content text-xs text-opacity-50">${escape($t("created-by"))}</p> <h2 class="text-base-content text-lg font-bold" data-svelte-h="svelte-1pxu4ke">Pouya Saadeghi</h2></div></a> <div class="flex flex-col items-center gap-4 text-left sm:flex-row">${validate_component(Sponsors, "Sponsors").$$render(
    $$result,
    {
      wrapperClasses: "flex-col sm:flex-row",
      classes: "bg-base-100"
    },
    {},
    {}
  )}</div></div></footer></div>`;
});
export {
  Footer as F
};
