import { c as create_ssr_component, v as validate_component } from "../../../../../chunks/ssr.js";
import { M as Mdsvex_blog } from "../../../../../chunks/mdsvex-blog.js";
const metadata = {
  "title": "What is daisyUI? (and other questions I get asked a lot)",
  "desc": "Is daisyUI against the Tailwind CSS philosophy? Are we going full circle? Why not just use Bootstrap? Here I answer some of the most common questions I get asked about daisyUI.",
  "published": true,
  "date": "2023-9-10",
  "author": "Pouya Saadeghi",
  "thumbnail": "/images/blog/daisyui-stars.jpg",
  "tags": ["Tailwind CSS", "Component Library"]
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `${validate_component(Mdsvex_blog, "Layout_MDSVEX_DEFAULT").$$render($$result, Object.assign({}, $$props, metadata), {}, {
    default: () => {
      return `<h2 id="what-is-daisyui" data-svelte-h="svelte-p8muly"><a aria-hidden="true" tabindex="-1" href="#what-is-daisyui"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>What is daisyUI?</h2> <p data-svelte-h="svelte-1pjr6sg"><a href="https://daisyui.com/" rel="nofollow">daisyUI</a> is a component library for Tailwind CSS. While Tailwind CSS provides utility classes for each CSS rule, daisyUI provides additional component class names to Tailwind CSS to make it faster and easier to build web pages.</p> <h2 id="is-daisyui-against-the-tailwind-css-philosophy" data-svelte-h="svelte-19890uc"><a aria-hidden="true" tabindex="-1" href="#is-daisyui-against-the-tailwind-css-philosophy"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>Is daisyUI against the Tailwind CSS philosophy?</h2> <p data-svelte-h="svelte-nni9cy">No.<br>
daisyUI is built on top of Tailwind CSS. Utility-first approach suggests that you should use utility classes for most of your CSS rules, but it doesn’t mean you should use <strong>utility classes only</strong>.<br>
Might be surprising to know but Tailwind CSS has an API for creating component classes (which is used by daisyUI) and Tailwind CSS itself also provides some component classes along with utility classes.</p> <blockquote data-svelte-h="svelte-10n2dza"><p>It’s called utility-first, not utility-only</p></blockquote> <h2 id="isnt-tailwind-css-enough-why-do-we-need-a-component-library-on-top-of-tailwind-css" data-svelte-h="svelte-fofem3"><a aria-hidden="true" tabindex="-1" href="#isnt-tailwind-css-enough-why-do-we-need-a-component-library-on-top-of-tailwind-css"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>Isn’t Tailwind CSS enough? Why do we need a component library on top of Tailwind CSS?</h2> <p data-svelte-h="svelte-yfc4f8">The truth is using <strong>utility classes only</strong>, is not practical for most people.</p> <ul data-svelte-h="svelte-5iluuy"><li>It needs design knowledge because you need to make design decisions for each single CSS rule you use for your elements.</li> <li>It need deep CSS knowledge because you’re basically using shorthand CSS rules for everything.</li> <li>It creates bloated HTML files. You need to add a hundred classes to a single element to style it.</li> <li>It’s not fast. You need to think and decide for each single CSS class you want to use.</li> <li>You need to consider every state of elements, like hover, focus, active, etc. and add classes for them too.</li> <li>It’s not easy to maintain. You end up with a lot of classes in your HTML files and it’s hard to find and change them.</li> <li>Using utility classes only is basically re-inventing the wheel a lot of times. You need to write a lot of CSS classes just to make a simple element which looks exactly like the one you made before.</li></ul> <blockquote data-svelte-h="svelte-szjy0g"><p>So instead of <strong>utility-only</strong> let’s keep it <strong>utility-first</strong><br>
Let’s use utility classes whenever we need customization<br>
and use component classes when we need speed</p></blockquote> <h2 id="but-we-already-had-bootstrap-are-we-going-full-circle" data-svelte-h="svelte-tfp1wd"><a aria-hidden="true" tabindex="-1" href="#but-we-already-had-bootstrap-are-we-going-full-circle"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>But we already had Bootstrap. Are we going full circle?</h2> <p data-svelte-h="svelte-qm14tu">Here’s where Tailwind CSS and the utility classes really shine.<br>
The biggest problem with Bootstrap and similar component libraries was that they were not customizable. You can’t change the design of a component without overriding a lot of CSS rules. Customizing Bootstrap was so hard that almost every single Bootstrap website looked the same.<br>
That wouldn’t be a problem when the component library is built on top of Tailwind CSS. You can customize the design of each component by simply adding utility classes to it. It can’t get any easier than that.<br>
Now you have the speed of component class names and the flexibility of utility class names.</p> <h2 id="who-is-daisyui-for" data-svelte-h="svelte-uoczq3"><a aria-hidden="true" tabindex="-1" href="#who-is-daisyui-for"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>Who is daisyUI for?</h2> <p data-svelte-h="svelte-apekpb">daisyUI is for people who want to build web pages fast but they also want to be able to customize the design of their components.</p> <p data-svelte-h="svelte-1evxyq1">Using <strong>utility classes only</strong> is not practical for most people. It’s not fast and it’s not easy to maintain.</p> <p data-svelte-h="svelte-23hg6v">Using <strong>component classes only</strong> not practical either. It’s not flexible and it’s not customizable.</p> <p data-svelte-h="svelte-15gtve6">There should be a balance between these two approaches where we have access to both speed and flexibility.</p> <blockquote data-svelte-h="svelte-1m20rqo"><p>Having component classes on top of utility classes is the best of both worlds.</p></blockquote> <h2 id="who-shouldnt-use-daisyui" data-svelte-h="svelte-1yg67kn"><a aria-hidden="true" tabindex="-1" href="#who-shouldnt-use-daisyui"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>Who shouldn’t use daisyUI?</h2> <p data-svelte-h="svelte-fyp2ve">daisyUI is not for you if you don’t need pre-made components. If you want to build everything from scratch, you don’t need daisyUI. Tailwind CSS provides all you need.</p> <h2 id="how-is-daisyui-different-from-other-tailwind-css-component-libraries" data-svelte-h="svelte-13ssn7q"><a aria-hidden="true" tabindex="-1" href="#how-is-daisyui-different-from-other-tailwind-css-component-libraries"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>How is daisyUI different from other Tailwind CSS component libraries?</h2> <p data-svelte-h="svelte-1gqltp8">daisyUI offers short, intuitive, and easy to remember class names.<br>
Other Tailwind CSS component libraries usually use the utility-only approach which results in bloated HTML files with a lot of class names.</p> <p data-svelte-h="svelte-kd3bpp">Basically with daisyUI you use a single <code>btn</code> class to make a button and then you can customize it with utility classes. With other component libraries you use copy/paste 100 class names to make a button and then you can customize it by editing them.</p> <h2 id="how-can-i-use-dailyui" data-svelte-h="svelte-thlhjh"><a aria-hidden="true" tabindex="-1" href="#how-can-i-use-dailyui"><span class="mr-1 opacity-20 hover:opacity-60 text-base font-bold inline-block align-middle relative -mt-1">#</span></a>How can I use dailyUI?</h2> <p data-svelte-h="svelte-rmo30b">To use daisyUI you need to install <a href="https://nodejs.org/en/download" rel="nofollow">Node.js</a> and <a href="https://tailwindcss.com/docs/installation" rel="nofollow">Tailwind CSS</a>.</p> <ol data-svelte-h="svelte-d22mxb"><li>install daisyUI with npm:</li></ol> <pre class="language-bash"><!-- HTML_TAG_START -->${`<code class="language-bash"><span class="token function">npm</span> i <span class="token parameter variable">-D</span> daisyui@latest</code>`}<!-- HTML_TAG_END --></pre> <ol start="2" data-svelte-h="svelte-1gft8iq"><li>Then add daisyUI to your tailwind.config.js files:</li></ol> <pre class="language-js"><!-- HTML_TAG_START -->${`<code class="language-js">module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">&#123;</span>
  <span class="token comment">//...</span>
  <span class="token literal-property property">plugins</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"daisyui"</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">&#125;</span></code>`}<!-- HTML_TAG_END --></pre> <p data-svelte-h="svelte-1n7jo9j">Read more about <a href="https://daisyui.com/docs/install/" rel="nofollow">how to install daisyUI</a> and <a href="https://daisyui.com/docs/use/" rel="nofollow">how to use daisyUI</a>.</p>`;
    }
  })}`;
});
export {
  Page as default,
  metadata
};
